version: '3'
services:

  nginx:
    build: ./nginx/
    #container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/wwwroot:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #command: nginx -g daemon off
    networks:
      devops_nw_front:
        ipv4_address: 172.31.0.2
      devops_nw_back:
        ipv4_address: 172.32.0.2

  webapi:
    build: ./webapi/
    container_name: webapi
    ports:
      - "5180:80"
    volumes:
      - "./webapi/data:/workspace"
    command: sh -c "cd /workspace/app/publish && dotnet dotnetWebApi.dll --urls=http://0.0.0.0:80"
    networks:
      devops_nw_back:
        ipv4_address: 172.32.0.3

  webapi-dev:
    build: ./webapi/
    container_name: webapi-dev
    ports:
      - "5080:80"
      - "5443:443"
      - "5022:22"
    volumes:
      - "./webapi/data:/workspace"
    command: /usr/sbin/sshd -D
    networks:
      devops_nw_back:
        ipv4_address: 172.32.1.3
 
  mosquitto:
    build: ./mqttd/
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mqttd/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mqttd/data:/var/lib/mosquitto/"
      - "./mqttd/log:/var/log/mosquitto"
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      devops_nw_front:
        ipv4_address: 172.31.0.4

  python-dev:
    build: ./python-dev/
    container_name: python-dev
    working_dir: /jupyterlab
    volumes:
      - ./python-dev/jupyterlab:/jupyterlab:rw
      - ./python-dev/workspace:/workspace:rw
    ports:
      - "8888:8888"
      - "5180:80"
      - "5122:22"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
    networks:
      devops_nw_back:
        ipv4_address: 172.32.1.10
 
networks:
  devops_nw_front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1

  devops_nw_back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
